"""
Add genre-specific games to fill catalog gaps.
Focus on: Horror, Racing, Sports, Platformer, Simulation, FPS, RPG, Roguelike, Survival
Also fills mobile-specific gaps.
"""

import firebase_admin
from firebase_admin import credentials, firestore
from datetime import datetime, timezone

if not firebase_admin._apps:
    cred = credentials.ApplicationDefault()
    firebase_admin.initialize_app(cred, {'projectId': 'playnxt-1a2c6'})

db = firestore.client()
games_ref = db.collection('games')

GENRE_FILL_GAMES = [
    # === HORROR GAMES ===
    {
        "game_id": "resident-evil-4-remake",
        "title": "Resident Evil 4",
        "platforms": ["pc", "playstation", "xbox"],
        "release_year": 2023,
        "genre_tags": ["horror", "action", "survival", "third-person-shooter"],
        "time_tags": [60, 90],
        "energy_level": "high",
        "mood_tags": ["tense", "action-packed", "scary"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo"],
        "description_short": "Rescue the president's daughter in this survival horror masterpiece.",
        "fun_fact": "The remake sold over 7 million copies in its first year.",
        "explanation_templates": {"time_fit": "Chapters provide good stopping points.", "mood_fit": "Intense horror action.", "stop_fit": "Frequent checkpoints and chapter breaks."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/2050650/Resident_Evil_4/"}
    },
    {
        "game_id": "resident-evil-2-remake",
        "title": "Resident Evil 2",
        "platforms": ["pc", "playstation", "xbox", "switch"],
        "release_year": 2019,
        "genre_tags": ["horror", "survival", "action"],
        "time_tags": [60, 90],
        "energy_level": "high",
        "mood_tags": ["scary", "tense", "atmospheric"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo"],
        "description_short": "Survive the Raccoon City zombie outbreak in this reimagined classic.",
        "fun_fact": "Won over 50 Game of the Year awards.",
        "explanation_templates": {"time_fit": "Save rooms let you take breaks.", "mood_fit": "Classic survival horror.", "stop_fit": "Save anytime at typewriters."},
        "subscription_services": ["game_pass"],
        "store_links": {"steam": "https://store.steampowered.com/app/883710/Resident_Evil_2/"}
    },
    {
        "game_id": "phasmophobia",
        "title": "Phasmophobia",
        "platforms": ["pc"],
        "release_year": 2020,
        "genre_tags": ["horror", "co-op", "simulation", "ghost"],
        "time_tags": [30, 60],
        "energy_level": "high",
        "mood_tags": ["scary", "tense", "cooperative"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "online_coop"],
        "description_short": "Hunt ghosts with friends using real paranormal equipment.",
        "fun_fact": "Uses voice recognition - ghosts can hear you through your mic.",
        "explanation_templates": {"time_fit": "Investigations take 15-30 minutes.", "mood_fit": "Terrifying co-op horror.", "stop_fit": "Complete investigations then stop."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/739630/Phasmophobia/"}
    },
    {
        "game_id": "dead-space-remake",
        "title": "Dead Space",
        "platforms": ["pc", "playstation", "xbox"],
        "release_year": 2023,
        "genre_tags": ["horror", "sci-fi", "action", "survival"],
        "time_tags": [60, 90],
        "energy_level": "high",
        "mood_tags": ["scary", "tense", "atmospheric"],
        "play_style": ["action"],
        "time_to_fun": "medium",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo"],
        "description_short": "Survive the Necromorph outbreak on the USG Ishimura.",
        "fun_fact": "The remake features zero loading screens for seamless immersion.",
        "explanation_templates": {"time_fit": "Chapters provide natural breaks.", "mood_fit": "Intense sci-fi horror.", "stop_fit": "Save at save stations."},
        "subscription_services": ["ea_play", "game_pass"],
        "store_links": {"steam": "https://store.steampowered.com/app/1693980/Dead_Space/"}
    },
    {
        "game_id": "outlast",
        "title": "Outlast",
        "platforms": ["pc", "playstation", "xbox", "switch"],
        "release_year": 2013,
        "genre_tags": ["horror", "survival", "stealth"],
        "time_tags": [60, 90],
        "energy_level": "high",
        "mood_tags": ["terrifying", "tense", "atmospheric"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo"],
        "description_short": "Investigate an asylum armed only with a night-vision camera.",
        "fun_fact": "You cannot fight enemies - only run and hide.",
        "explanation_templates": {"time_fit": "Chapters provide stopping points.", "mood_fit": "Pure terror with no combat.", "stop_fit": "Checkpoint saves between areas."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/238320/Outlast/"}
    },
    {
        "game_id": "little-nightmares",
        "title": "Little Nightmares",
        "platforms": ["pc", "playstation", "xbox", "switch", "mobile"],
        "release_year": 2017,
        "genre_tags": ["horror", "puzzle", "platformer", "indie"],
        "time_tags": [30, 60],
        "energy_level": "medium",
        "mood_tags": ["creepy", "atmospheric", "tense"],
        "play_style": ["puzzle", "action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo"],
        "description_short": "Guide Six through a nightmarish vessel called The Maw.",
        "fun_fact": "The entire game can be completed in about 4 hours.",
        "explanation_templates": {"time_fit": "Chapters take 30-45 minutes.", "mood_fit": "Atmospheric puzzle horror.", "stop_fit": "Save between chapters."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/424840/Little_Nightmares/"}
    },
    {
        "game_id": "little-nightmares-2",
        "title": "Little Nightmares II",
        "platforms": ["pc", "playstation", "xbox", "switch", "mobile"],
        "release_year": 2021,
        "genre_tags": ["horror", "puzzle", "platformer", "indie"],
        "time_tags": [30, 60],
        "energy_level": "medium",
        "mood_tags": ["creepy", "atmospheric", "tense"],
        "play_style": ["puzzle", "action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo"],
        "description_short": "Mono and Six face new nightmares in the Pale City.",
        "fun_fact": "Features light combat unlike the first game.",
        "explanation_templates": {"time_fit": "Chapters provide natural breaks.", "mood_fit": "Creepy co-op horror puzzles.", "stop_fit": "Checkpoint saves frequently."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/860510/Little_Nightmares_II/"}
    },
    {
        "game_id": "alien-isolation",
        "title": "Alien: Isolation",
        "platforms": ["pc", "playstation", "xbox", "switch", "mobile"],
        "release_year": 2014,
        "genre_tags": ["horror", "survival", "stealth", "sci-fi"],
        "time_tags": [60, 90],
        "energy_level": "high",
        "mood_tags": ["terrifying", "tense", "immersive"],
        "play_style": ["action"],
        "time_to_fun": "medium",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo"],
        "description_short": "Survive against an unstoppable Xenomorph on a space station.",
        "fun_fact": "The alien learns from your hiding strategies.",
        "explanation_templates": {"time_fit": "Missions provide stopping points.", "mood_fit": "Authentic Alien horror.", "stop_fit": "Save at emergency phones."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/214490/Alien_Isolation/"}
    },
    {
        "game_id": "until-dawn",
        "title": "Until Dawn",
        "platforms": ["pc", "playstation"],
        "release_year": 2015,
        "genre_tags": ["horror", "interactive-story", "narrative"],
        "time_tags": [60, 90],
        "energy_level": "medium",
        "mood_tags": ["scary", "tense", "cinematic"],
        "play_style": ["narrative"],
        "time_to_fun": "medium",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo"],
        "description_short": "Your choices determine who survives the night in this horror thriller.",
        "fun_fact": "Every character can live or die based on your decisions.",
        "explanation_templates": {"time_fit": "Chapters take 30-45 minutes.", "mood_fit": "Interactive horror movie.", "stop_fit": "Autosaves between chapters."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/2172010/Until_Dawn/"}
    },
    {
        "game_id": "the-quarry",
        "title": "The Quarry",
        "platforms": ["pc", "playstation", "xbox"],
        "release_year": 2022,
        "genre_tags": ["horror", "interactive-story", "narrative"],
        "time_tags": [60, 90],
        "energy_level": "medium",
        "mood_tags": ["scary", "cinematic", "tense"],
        "play_style": ["narrative"],
        "time_to_fun": "medium",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "local_coop"],
        "description_short": "Survive a night at a haunted summer camp.",
        "fun_fact": "Features Hollywood actors including David Arquette.",
        "explanation_templates": {"time_fit": "Chapters take 30-45 minutes.", "mood_fit": "Teen slasher movie experience.", "stop_fit": "Save between chapters."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/1260590/The_Quarry/"}
    },

    # === RACING GAMES ===
    {
        "game_id": "forza-horizon-5",
        "title": "Forza Horizon 5",
        "platforms": ["pc", "xbox"],
        "release_year": 2021,
        "genre_tags": ["racing", "open-world", "simulation"],
        "time_tags": [30, 60, 90],
        "energy_level": "medium",
        "mood_tags": ["exciting", "relaxing", "adventurous"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "anytime",
        "multiplayer_modes": ["solo", "online_coop", "competitive"],
        "description_short": "Race across a stunning open-world Mexico.",
        "fun_fact": "Features over 700 cars and the largest Forza map ever.",
        "explanation_templates": {"time_fit": "Races take 5-15 minutes, explore freely.", "mood_fit": "Accessible racing fun.", "stop_fit": "Stop anytime in open world."},
        "subscription_services": ["game_pass"],
        "store_links": {"steam": "https://store.steampowered.com/app/1551360/Forza_Horizon_5/"}
    },
    {
        "game_id": "gran-turismo-7",
        "title": "Gran Turismo 7",
        "platforms": ["playstation"],
        "release_year": 2022,
        "genre_tags": ["racing", "simulation", "cars"],
        "time_tags": [30, 60, 90],
        "energy_level": "medium",
        "mood_tags": ["focused", "relaxing", "rewarding"],
        "play_style": ["action"],
        "time_to_fun": "medium",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "competitive"],
        "description_short": "The definitive PlayStation racing simulation.",
        "fun_fact": "Called 'The Real Driving Simulator' since 1997.",
        "explanation_templates": {"time_fit": "Races vary from 5-30 minutes.", "mood_fit": "Authentic racing experience.", "stop_fit": "Save between races."},
        "subscription_services": [],
        "store_links": {}
    },
    {
        "game_id": "mario-kart-8-deluxe",
        "title": "Mario Kart 8 Deluxe",
        "platforms": ["switch"],
        "release_year": 2017,
        "genre_tags": ["racing", "party", "arcade", "kart"],
        "time_tags": [15, 30, 60],
        "energy_level": "medium",
        "mood_tags": ["fun", "competitive", "chaotic"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "local_coop", "online_coop", "competitive"],
        "description_short": "Race with Mario characters in this beloved kart racer.",
        "fun_fact": "One of the best-selling games of all time with over 60 million copies.",
        "explanation_templates": {"time_fit": "Races take 2-3 minutes each.", "mood_fit": "Fun competitive racing.", "stop_fit": "Stop after any race."},
        "subscription_services": [],
        "store_links": {}
    },
    {
        "game_id": "need-for-speed-unbound",
        "title": "Need for Speed Unbound",
        "platforms": ["pc", "playstation", "xbox"],
        "release_year": 2022,
        "genre_tags": ["racing", "open-world", "arcade", "street"],
        "time_tags": [30, 60],
        "energy_level": "high",
        "mood_tags": ["stylish", "exciting", "rebellious"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "anytime",
        "multiplayer_modes": ["solo", "online_coop", "competitive"],
        "description_short": "Street racing with a unique anime-inspired art style.",
        "fun_fact": "Features a distinctive cel-shaded visual effect on cars.",
        "explanation_templates": {"time_fit": "Events take 5-15 minutes.", "mood_fit": "Stylish street racing.", "stop_fit": "Save progress at safehouses."},
        "subscription_services": ["ea_play", "game_pass"],
        "store_links": {"steam": "https://store.steampowered.com/app/1846380/Need_for_Speed_Unbound/"}
    },
    {
        "game_id": "f1-24",
        "title": "F1 24",
        "platforms": ["pc", "playstation", "xbox"],
        "release_year": 2024,
        "genre_tags": ["racing", "simulation", "sports", "formula-one"],
        "time_tags": [30, 60, 90],
        "energy_level": "high",
        "mood_tags": ["competitive", "focused", "realistic"],
        "play_style": ["action"],
        "time_to_fun": "medium",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "online_coop", "competitive"],
        "description_short": "Official Formula 1 racing with all teams and tracks.",
        "fun_fact": "Includes full F1, F2, and F3 championships.",
        "explanation_templates": {"time_fit": "Races take 15-60 minutes depending on settings.", "mood_fit": "Authentic F1 racing.", "stop_fit": "Save mid-season anytime."},
        "subscription_services": ["ea_play"],
        "store_links": {"steam": "https://store.steampowered.com/app/2488620/F1_24/"}
    },
    {
        "game_id": "dirt-rally-2",
        "title": "Dirt Rally 2.0",
        "platforms": ["pc", "playstation", "xbox"],
        "release_year": 2019,
        "genre_tags": ["racing", "simulation", "rally"],
        "time_tags": [30, 60],
        "energy_level": "high",
        "mood_tags": ["intense", "challenging", "rewarding"],
        "play_style": ["action"],
        "time_to_fun": "medium",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "competitive"],
        "description_short": "Hardcore rally racing across diverse terrains.",
        "fun_fact": "Considered one of the most realistic rally games ever made.",
        "explanation_templates": {"time_fit": "Stages take 5-15 minutes.", "mood_fit": "Challenging rally simulation.", "stop_fit": "Stop between rally stages."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/690790/DiRT_Rally_20/"}
    },
    {
        "game_id": "rocket-league",
        "title": "Rocket League",
        "platforms": ["pc", "playstation", "xbox", "switch"],
        "release_year": 2015,
        "genre_tags": ["racing", "sports", "soccer", "arcade"],
        "time_tags": [15, 30],
        "energy_level": "high",
        "mood_tags": ["competitive", "exciting", "fun"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "local_coop", "online_coop", "competitive"],
        "description_short": "Soccer with rocket-powered cars.",
        "fun_fact": "Went free-to-play in 2020 and has over 90 million players.",
        "explanation_templates": {"time_fit": "Matches take 5-7 minutes.", "mood_fit": "Fast-paced car soccer.", "stop_fit": "Complete matches then stop."},
        "subscription_services": [],
        "store_links": {}
    },
    {
        "game_id": "wreckfest",
        "title": "Wreckfest",
        "platforms": ["pc", "playstation", "xbox", "switch", "mobile"],
        "release_year": 2018,
        "genre_tags": ["racing", "destruction", "arcade"],
        "time_tags": [15, 30],
        "energy_level": "high",
        "mood_tags": ["chaotic", "fun", "destructive"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "competitive"],
        "description_short": "Demolition derby racing with realistic damage.",
        "fun_fact": "From the creators of the classic FlatOut series.",
        "explanation_templates": {"time_fit": "Events take 5-10 minutes.", "mood_fit": "Satisfying car destruction.", "stop_fit": "Complete events then stop."},
        "subscription_services": ["game_pass"],
        "store_links": {"steam": "https://store.steampowered.com/app/228380/Wreckfest/"}
    },

    # === SPORTS GAMES ===
    {
        "game_id": "nba-2k25",
        "title": "NBA 2K25",
        "platforms": ["pc", "playstation", "xbox", "switch"],
        "release_year": 2024,
        "genre_tags": ["sports", "basketball", "simulation"],
        "time_tags": [30, 60],
        "energy_level": "medium",
        "mood_tags": ["competitive", "sports", "social"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "local_coop", "online_coop", "competitive"],
        "description_short": "The premier basketball simulation experience.",
        "fun_fact": "MyCareer mode lets you live the life of an NBA player.",
        "explanation_templates": {"time_fit": "Games take 20-40 minutes.", "mood_fit": "Authentic NBA action.", "stop_fit": "Save between games."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/2338770/NBA_2K25/"}
    },
    {
        "game_id": "ea-sports-fc-25",
        "title": "EA Sports FC 25",
        "platforms": ["pc", "playstation", "xbox", "switch"],
        "release_year": 2024,
        "genre_tags": ["sports", "soccer", "simulation"],
        "time_tags": [15, 30, 60],
        "energy_level": "medium",
        "mood_tags": ["competitive", "sports", "social"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "local_coop", "online_coop", "competitive"],
        "description_short": "The world's most popular football game.",
        "fun_fact": "First year as EA Sports FC after the FIFA license ended.",
        "explanation_templates": {"time_fit": "Matches take 10-20 minutes.", "mood_fit": "Authentic football action.", "stop_fit": "Complete matches then stop."},
        "subscription_services": ["ea_play"],
        "store_links": {"steam": "https://store.steampowered.com/app/2669320/EA_SPORTS_FC_25/"}
    },
    {
        "game_id": "madden-nfl-25",
        "title": "Madden NFL 25",
        "platforms": ["pc", "playstation", "xbox"],
        "release_year": 2024,
        "genre_tags": ["sports", "football", "simulation"],
        "time_tags": [30, 60],
        "energy_level": "medium",
        "mood_tags": ["competitive", "sports", "strategic"],
        "play_style": ["action", "strategy"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "local_coop", "online_coop", "competitive"],
        "description_short": "The official NFL football simulation.",
        "fun_fact": "Named after legendary coach John Madden since 1988.",
        "explanation_templates": {"time_fit": "Games take 30-45 minutes.", "mood_fit": "Strategic football action.", "stop_fit": "Save at halftime or after games."},
        "subscription_services": ["ea_play"],
        "store_links": {"steam": "https://store.steampowered.com/app/2417330/Madden_NFL_25/"}
    },
    {
        "game_id": "mlb-the-show-24",
        "title": "MLB The Show 24",
        "platforms": ["playstation", "xbox", "switch"],
        "release_year": 2024,
        "genre_tags": ["sports", "baseball", "simulation"],
        "time_tags": [30, 60],
        "energy_level": "low",
        "mood_tags": ["relaxing", "sports", "strategic"],
        "play_style": ["action", "strategy"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "local_coop", "competitive"],
        "description_short": "The premier baseball simulation experience.",
        "fun_fact": "Originally PlayStation exclusive, now on all platforms.",
        "explanation_templates": {"time_fit": "Games take 20-40 minutes.", "mood_fit": "Relaxing baseball action.", "stop_fit": "Save between innings."},
        "subscription_services": ["game_pass"],
        "store_links": {}
    },
    {
        "game_id": "tony-hawk-1-2",
        "title": "Tony Hawk's Pro Skater 1 + 2",
        "platforms": ["pc", "playstation", "xbox", "switch"],
        "release_year": 2020,
        "genre_tags": ["sports", "skateboarding", "arcade"],
        "time_tags": [15, 30, 60],
        "energy_level": "medium",
        "mood_tags": ["fun", "nostalgic", "satisfying"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "anytime",
        "multiplayer_modes": ["solo", "local_coop", "competitive"],
        "description_short": "Classic skateboarding games remade in stunning detail.",
        "fun_fact": "Faithfully recreates the originals with modern graphics.",
        "explanation_templates": {"time_fit": "Sessions last 2 minutes, play as many as you want.", "mood_fit": "Satisfying trick combos.", "stop_fit": "Stop after any session."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/2395210/Tony_Hawks_Pro_Skater_1__2/"}
    },
    {
        "game_id": "wwe-2k24",
        "title": "WWE 2K24",
        "platforms": ["pc", "playstation", "xbox"],
        "release_year": 2024,
        "genre_tags": ["sports", "wrestling", "fighting"],
        "time_tags": [15, 30, 60],
        "energy_level": "high",
        "mood_tags": ["exciting", "action-packed", "dramatic"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "local_coop", "competitive"],
        "description_short": "Create and fight as WWE superstars.",
        "fun_fact": "Celebrates 40 years of WrestleMania.",
        "explanation_templates": {"time_fit": "Matches take 10-20 minutes.", "mood_fit": "Exciting wrestling action.", "stop_fit": "Save between matches."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/2315910/WWE_2K24/"}
    },

    # === PLATFORMER GAMES ===
    {
        "game_id": "super-mario-odyssey",
        "title": "Super Mario Odyssey",
        "platforms": ["switch"],
        "release_year": 2017,
        "genre_tags": ["platformer", "3d", "adventure", "collectathon"],
        "time_tags": [30, 60, 90],
        "energy_level": "medium",
        "mood_tags": ["joyful", "adventurous", "creative"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "anytime",
        "multiplayer_modes": ["solo", "local_coop"],
        "description_short": "Mario travels the world in his most ambitious adventure.",
        "fun_fact": "You can possess enemies with Mario's cap, Cappy.",
        "explanation_templates": {"time_fit": "Explore kingdoms at your own pace.", "mood_fit": "Joyful Mario adventure.", "stop_fit": "Save and stop anytime."},
        "subscription_services": [],
        "store_links": {}
    },
    {
        "game_id": "super-mario-bros-wonder",
        "title": "Super Mario Bros. Wonder",
        "platforms": ["switch"],
        "release_year": 2023,
        "genre_tags": ["platformer", "2d", "multiplayer"],
        "time_tags": [15, 30, 60],
        "energy_level": "medium",
        "mood_tags": ["fun", "surprising", "creative"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "anytime",
        "multiplayer_modes": ["solo", "local_coop"],
        "description_short": "2D Mario with wild transformations and surprises.",
        "fun_fact": "Wonder effects transform levels in unexpected ways.",
        "explanation_templates": {"time_fit": "Levels take 2-5 minutes.", "mood_fit": "Surprising platforming fun.", "stop_fit": "Stop after any level."},
        "subscription_services": [],
        "store_links": {}
    },
    {
        "game_id": "celeste",
        "title": "Celeste",
        "platforms": ["pc", "playstation", "xbox", "switch"],
        "release_year": 2018,
        "genre_tags": ["platformer", "2d", "indie", "difficult"],
        "time_tags": [30, 60],
        "energy_level": "high",
        "mood_tags": ["challenging", "rewarding", "emotional"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo"],
        "description_short": "Climb a mountain in this challenging precision platformer.",
        "fun_fact": "Deals with themes of anxiety and self-acceptance.",
        "explanation_templates": {"time_fit": "Chapters provide natural breaks.", "mood_fit": "Challenging but rewarding.", "stop_fit": "Frequent checkpoints."},
        "subscription_services": ["game_pass"],
        "store_links": {"steam": "https://store.steampowered.com/app/504230/Celeste/"}
    },
    {
        "game_id": "hollow-knight",
        "title": "Hollow Knight",
        "platforms": ["pc", "playstation", "xbox", "switch"],
        "release_year": 2017,
        "genre_tags": ["platformer", "metroidvania", "indie", "action"],
        "time_tags": [60, 90],
        "energy_level": "medium",
        "mood_tags": ["atmospheric", "challenging", "mysterious"],
        "play_style": ["action"],
        "time_to_fun": "medium",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo"],
        "description_short": "Explore a vast underground kingdom of bugs.",
        "fun_fact": "Offers 50+ hours of content for a $15 game.",
        "explanation_templates": {"time_fit": "Explore at your own pace.", "mood_fit": "Deep metroidvania exploration.", "stop_fit": "Save at benches."},
        "subscription_services": ["game_pass"],
        "store_links": {"steam": "https://store.steampowered.com/app/367520/Hollow_Knight/"}
    },
    {
        "game_id": "ori-will-of-wisps",
        "title": "Ori and the Will of the Wisps",
        "platforms": ["pc", "xbox", "switch"],
        "release_year": 2020,
        "genre_tags": ["platformer", "metroidvania", "indie", "action"],
        "time_tags": [30, 60],
        "energy_level": "medium",
        "mood_tags": ["beautiful", "emotional", "challenging"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "anytime",
        "multiplayer_modes": ["solo"],
        "description_short": "A stunningly beautiful metroidvania adventure.",
        "fun_fact": "Hand-painted art with an orchestral soundtrack.",
        "explanation_templates": {"time_fit": "Explore at your own pace.", "mood_fit": "Beautiful and emotional.", "stop_fit": "Save anywhere you want."},
        "subscription_services": ["game_pass"],
        "store_links": {"steam": "https://store.steampowered.com/app/1057090/Ori_and_the_Will_of_the_Wisps/"}
    },
    {
        "game_id": "rayman-legends",
        "title": "Rayman Legends",
        "platforms": ["pc", "playstation", "xbox", "switch"],
        "release_year": 2013,
        "genre_tags": ["platformer", "2d", "co-op", "rhythm"],
        "time_tags": [15, 30, 60],
        "energy_level": "medium",
        "mood_tags": ["fun", "colorful", "chaotic"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "local_coop"],
        "description_short": "Beautiful 2D platforming with up to 4 players.",
        "fun_fact": "Music levels sync gameplay to famous songs.",
        "explanation_templates": {"time_fit": "Levels take 5-10 minutes.", "mood_fit": "Fun cooperative platforming.", "stop_fit": "Stop after any level."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/242550/Rayman_Legends/"}
    },
    {
        "game_id": "crash-4",
        "title": "Crash Bandicoot 4: It's About Time",
        "platforms": ["pc", "playstation", "xbox", "switch"],
        "release_year": 2020,
        "genre_tags": ["platformer", "3d", "challenging"],
        "time_tags": [30, 60],
        "energy_level": "medium",
        "mood_tags": ["fun", "challenging", "nostalgic"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "local_coop"],
        "description_short": "The true sequel to the original Crash trilogy.",
        "fun_fact": "Features dimensional masks that change gameplay mechanics.",
        "explanation_templates": {"time_fit": "Levels take 10-15 minutes.", "mood_fit": "Challenging platforming fun.", "stop_fit": "Frequent checkpoints."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/1378310/Crash_Bandicoot_4_Its_About_Time/"}
    },
    {
        "game_id": "shovel-knight",
        "title": "Shovel Knight: Treasure Trove",
        "platforms": ["pc", "playstation", "xbox", "switch"],
        "release_year": 2014,
        "genre_tags": ["platformer", "2d", "retro", "indie"],
        "time_tags": [30, 60],
        "energy_level": "medium",
        "mood_tags": ["nostalgic", "challenging", "fun"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "local_coop"],
        "description_short": "Retro-style platformer with modern design sensibilities.",
        "fun_fact": "Includes four complete campaigns in one package.",
        "explanation_templates": {"time_fit": "Levels take 10-15 minutes.", "mood_fit": "Classic platforming action.", "stop_fit": "Save between levels."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/250760/Shovel_Knight_Treasure_Trove/"}
    },

    # === SIMULATION GAMES ===
    {
        "game_id": "cities-skylines-2",
        "title": "Cities: Skylines II",
        "platforms": ["pc", "playstation", "xbox"],
        "release_year": 2023,
        "genre_tags": ["simulation", "city-builder", "strategy"],
        "time_tags": [60, 90],
        "energy_level": "low",
        "mood_tags": ["relaxing", "creative", "strategic"],
        "play_style": ["sandbox_creative", "strategy"],
        "time_to_fun": "medium",
        "stop_friendliness": "anytime",
        "multiplayer_modes": ["solo"],
        "description_short": "Build and manage massive, detailed cities.",
        "fun_fact": "Cities can grow to millions of citizens.",
        "explanation_templates": {"time_fit": "Play at your own pace.", "mood_fit": "Relaxing city building.", "stop_fit": "Save and stop anytime."},
        "subscription_services": ["game_pass"],
        "store_links": {"steam": "https://store.steampowered.com/app/949230/Cities_Skylines_II/"}
    },
    {
        "game_id": "two-point-campus",
        "title": "Two Point Campus",
        "platforms": ["pc", "playstation", "xbox", "switch"],
        "release_year": 2022,
        "genre_tags": ["simulation", "management", "comedy"],
        "time_tags": [30, 60],
        "energy_level": "low",
        "mood_tags": ["fun", "relaxing", "humorous"],
        "play_style": ["strategy"],
        "time_to_fun": "short",
        "stop_friendliness": "anytime",
        "multiplayer_modes": ["solo"],
        "description_short": "Build and run wacky universities.",
        "fun_fact": "Courses include Knight School and Gastronomy.",
        "explanation_templates": {"time_fit": "Play scenarios at your pace.", "mood_fit": "Humorous management.", "stop_fit": "Save anytime."},
        "subscription_services": ["game_pass"],
        "store_links": {"steam": "https://store.steampowered.com/app/1649080/Two_Point_Campus/"}
    },
    {
        "game_id": "powerwash-simulator",
        "title": "PowerWash Simulator",
        "platforms": ["pc", "playstation", "xbox", "switch"],
        "release_year": 2022,
        "genre_tags": ["simulation", "relaxing", "satisfying"],
        "time_tags": [30, 60],
        "energy_level": "low",
        "mood_tags": ["relaxing", "satisfying", "zen"],
        "play_style": ["sandbox_creative"],
        "time_to_fun": "short",
        "stop_friendliness": "anytime",
        "multiplayer_modes": ["solo", "online_coop"],
        "description_short": "Clean dirt and grime in this oddly satisfying sim.",
        "fun_fact": "Has become a surprisingly popular streaming game.",
        "explanation_templates": {"time_fit": "Jobs take 20-60 minutes.", "mood_fit": "Incredibly satisfying cleaning.", "stop_fit": "Progress saves automatically."},
        "subscription_services": ["game_pass"],
        "store_links": {"steam": "https://store.steampowered.com/app/1290000/PowerWash_Simulator/"}
    },
    {
        "game_id": "house-flipper-2",
        "title": "House Flipper 2",
        "platforms": ["pc", "playstation", "xbox"],
        "release_year": 2023,
        "genre_tags": ["simulation", "renovation", "relaxing"],
        "time_tags": [30, 60],
        "energy_level": "low",
        "mood_tags": ["relaxing", "creative", "satisfying"],
        "play_style": ["sandbox_creative"],
        "time_to_fun": "short",
        "stop_friendliness": "anytime",
        "multiplayer_modes": ["solo"],
        "description_short": "Buy, renovate, and flip houses for profit.",
        "fun_fact": "You can now build from the ground up.",
        "explanation_templates": {"time_fit": "Renovate at your own pace.", "mood_fit": "Relaxing home improvement.", "stop_fit": "Save anytime."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/1190970/House_Flipper_2/"}
    },
    {
        "game_id": "planet-coaster-2",
        "title": "Planet Coaster 2",
        "platforms": ["pc", "playstation", "xbox"],
        "release_year": 2024,
        "genre_tags": ["simulation", "theme-park", "building"],
        "time_tags": [60, 90],
        "energy_level": "low",
        "mood_tags": ["creative", "relaxing", "fun"],
        "play_style": ["sandbox_creative"],
        "time_to_fun": "medium",
        "stop_friendliness": "anytime",
        "multiplayer_modes": ["solo"],
        "description_short": "Design and build your dream theme park.",
        "fun_fact": "Now includes water parks and wave pools.",
        "explanation_templates": {"time_fit": "Build at your own pace.", "mood_fit": "Creative park design.", "stop_fit": "Save anytime."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/2207730/Planet_Coaster_2/"}
    },
    {
        "game_id": "flight-simulator-2024",
        "title": "Microsoft Flight Simulator 2024",
        "platforms": ["pc", "xbox"],
        "release_year": 2024,
        "genre_tags": ["simulation", "flight", "open-world"],
        "time_tags": [30, 60, 90],
        "energy_level": "low",
        "mood_tags": ["relaxing", "immersive", "adventurous"],
        "play_style": ["sandbox_creative"],
        "time_to_fun": "medium",
        "stop_friendliness": "anytime",
        "multiplayer_modes": ["solo", "online_coop"],
        "description_short": "Fly anywhere in the world with photorealistic graphics.",
        "fun_fact": "Uses real-world satellite data to recreate the entire Earth.",
        "explanation_templates": {"time_fit": "Flights can be any length you want.", "mood_fit": "Zen-like flying experience.", "stop_fit": "Land and stop anytime."},
        "subscription_services": ["game_pass"],
        "store_links": {"steam": "https://store.steampowered.com/app/2537590/Microsoft_Flight_Simulator_2024/"}
    },

    # === FPS GAMES ===
    {
        "game_id": "halo-infinite",
        "title": "Halo Infinite",
        "platforms": ["pc", "xbox"],
        "release_year": 2021,
        "genre_tags": ["fps", "shooter", "sci-fi", "multiplayer"],
        "time_tags": [15, 30, 60],
        "energy_level": "high",
        "mood_tags": ["competitive", "action-packed", "epic"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "online_coop", "competitive"],
        "description_short": "Master Chief returns in this open-world Halo adventure.",
        "fun_fact": "Multiplayer is free-to-play.",
        "explanation_templates": {"time_fit": "Matches take 10-15 minutes.", "mood_fit": "Classic arena shooter action.", "stop_fit": "Complete matches then stop."},
        "subscription_services": ["game_pass"],
        "store_links": {"steam": "https://store.steampowered.com/app/1240440/Halo_Infinite/"}
    },
    {
        "game_id": "doom-eternal",
        "title": "DOOM Eternal",
        "platforms": ["pc", "playstation", "xbox", "switch"],
        "release_year": 2020,
        "genre_tags": ["fps", "shooter", "action", "demons"],
        "time_tags": [30, 60],
        "energy_level": "high",
        "mood_tags": ["intense", "action-packed", "adrenaline"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "competitive"],
        "description_short": "Rip and tear through demons at breakneck speed.",
        "fun_fact": "Designed around aggressive combat - standing still means death.",
        "explanation_templates": {"time_fit": "Missions take 30-60 minutes.", "mood_fit": "Pure adrenaline action.", "stop_fit": "Frequent checkpoints."},
        "subscription_services": ["game_pass"],
        "store_links": {"steam": "https://store.steampowered.com/app/782330/DOOM_Eternal/"}
    },
    {
        "game_id": "counter-strike-2",
        "title": "Counter-Strike 2",
        "platforms": ["pc"],
        "release_year": 2023,
        "genre_tags": ["fps", "shooter", "competitive", "tactical"],
        "time_tags": [30, 60],
        "energy_level": "high",
        "mood_tags": ["competitive", "tactical", "intense"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "commitment",
        "multiplayer_modes": ["competitive"],
        "description_short": "The legendary tactical shooter, rebuilt.",
        "fun_fact": "The most-played game on Steam.",
        "explanation_templates": {"time_fit": "Matches take 30-45 minutes.", "mood_fit": "Intense tactical gameplay.", "stop_fit": "Commit to full matches."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/730/CounterStrike_2/"}
    },
    {
        "game_id": "valorant",
        "title": "VALORANT",
        "platforms": ["pc"],
        "release_year": 2020,
        "genre_tags": ["fps", "shooter", "competitive", "tactical"],
        "time_tags": [30, 60],
        "energy_level": "high",
        "mood_tags": ["competitive", "tactical", "team-based"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "commitment",
        "multiplayer_modes": ["competitive"],
        "description_short": "Tactical shooter with unique agent abilities.",
        "fun_fact": "Combines Counter-Strike gunplay with Overwatch-style abilities.",
        "explanation_templates": {"time_fit": "Matches take 30-40 minutes.", "mood_fit": "Strategic team combat.", "stop_fit": "Commit to full matches."},
        "subscription_services": [],
        "store_links": {}
    },
    {
        "game_id": "overwatch-2",
        "title": "Overwatch 2",
        "platforms": ["pc", "playstation", "xbox", "switch"],
        "release_year": 2022,
        "genre_tags": ["fps", "shooter", "hero", "multiplayer"],
        "time_tags": [15, 30],
        "energy_level": "high",
        "mood_tags": ["competitive", "team-based", "exciting"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["competitive", "online_coop"],
        "description_short": "Hero-based team shooter with unique abilities.",
        "fun_fact": "Free-to-play with over 35 playable heroes.",
        "explanation_templates": {"time_fit": "Matches take 10-20 minutes.", "mood_fit": "Fast hero-based combat.", "stop_fit": "Complete matches then stop."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/2357570/Overwatch_2/"}
    },
    {
        "game_id": "rainbow-six-siege",
        "title": "Rainbow Six Siege",
        "platforms": ["pc", "playstation", "xbox"],
        "release_year": 2015,
        "genre_tags": ["fps", "shooter", "tactical", "competitive"],
        "time_tags": [30, 60],
        "energy_level": "high",
        "mood_tags": ["tactical", "competitive", "tense"],
        "play_style": ["action", "strategy"],
        "time_to_fun": "medium",
        "stop_friendliness": "commitment",
        "multiplayer_modes": ["competitive", "online_coop"],
        "description_short": "Tactical shooter with destructible environments.",
        "fun_fact": "Over 70 unique operators with different gadgets.",
        "explanation_templates": {"time_fit": "Matches take 20-30 minutes.", "mood_fit": "Strategic tactical gameplay.", "stop_fit": "Commit to full matches."},
        "subscription_services": ["game_pass"],
        "store_links": {"steam": "https://store.steampowered.com/app/359550/Tom_Clancys_Rainbow_Six_Siege/"}
    },
    {
        "game_id": "destiny-2",
        "title": "Destiny 2",
        "platforms": ["pc", "playstation", "xbox"],
        "release_year": 2017,
        "genre_tags": ["fps", "shooter", "mmo", "looter"],
        "time_tags": [30, 60, 90],
        "energy_level": "high",
        "mood_tags": ["epic", "cooperative", "rewarding"],
        "play_style": ["action"],
        "time_to_fun": "medium",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "online_coop", "competitive"],
        "description_short": "Sci-fi looter shooter with raids and dungeons.",
        "fun_fact": "Base game is free-to-play.",
        "explanation_templates": {"time_fit": "Activities range from 15 minutes to 2 hours.", "mood_fit": "Epic sci-fi combat.", "stop_fit": "Stop between activities."},
        "subscription_services": ["game_pass"],
        "store_links": {"steam": "https://store.steampowered.com/app/1085660/Destiny_2/"}
    },

    # === RPG GAMES ===
    {
        "game_id": "baldurs-gate-3",
        "title": "Baldur's Gate 3",
        "platforms": ["pc", "playstation", "xbox"],
        "release_year": 2023,
        "genre_tags": ["rpg", "turn-based", "fantasy", "crpg"],
        "time_tags": [60, 90],
        "energy_level": "medium",
        "mood_tags": ["immersive", "strategic", "story-driven"],
        "play_style": ["narrative", "strategy"],
        "time_to_fun": "medium",
        "stop_friendliness": "anytime",
        "multiplayer_modes": ["solo", "online_coop"],
        "description_short": "Epic D&D RPG with unprecedented freedom and choice.",
        "fun_fact": "Won Game of the Year at every major awards show.",
        "explanation_templates": {"time_fit": "Save anywhere, play at your pace.", "mood_fit": "Deep roleplaying experience.", "stop_fit": "Save anywhere anytime."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/1086940/Baldurs_Gate_3/"}
    },
    {
        "game_id": "elden-ring",
        "title": "Elden Ring",
        "platforms": ["pc", "playstation", "xbox"],
        "release_year": 2022,
        "genre_tags": ["rpg", "action", "open-world", "souls-like"],
        "time_tags": [60, 90],
        "energy_level": "high",
        "mood_tags": ["challenging", "epic", "mysterious"],
        "play_style": ["action"],
        "time_to_fun": "medium",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "online_coop", "competitive"],
        "description_short": "Open-world Souls game co-created with George R.R. Martin.",
        "fun_fact": "Sold over 25 million copies in its first year.",
        "explanation_templates": {"time_fit": "Explore at your own pace.", "mood_fit": "Challenging epic adventure.", "stop_fit": "Rest at Sites of Grace."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/1245620/ELDEN_RING/"}
    },
    {
        "game_id": "persona-5-royal",
        "title": "Persona 5 Royal",
        "platforms": ["pc", "playstation", "xbox", "switch"],
        "release_year": 2019,
        "genre_tags": ["rpg", "jrpg", "turn-based", "social-sim"],
        "time_tags": [60, 90],
        "energy_level": "medium",
        "mood_tags": ["stylish", "story-driven", "strategic"],
        "play_style": ["narrative", "strategy"],
        "time_to_fun": "long",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo"],
        "description_short": "Stylish JRPG about teenage phantom thieves.",
        "fun_fact": "The complete experience takes 100+ hours.",
        "explanation_templates": {"time_fit": "Save at the end of each day.", "mood_fit": "Stylish turn-based combat.", "stop_fit": "Daily structure provides breaks."},
        "subscription_services": ["game_pass"],
        "store_links": {"steam": "https://store.steampowered.com/app/1687950/Persona_5_Royal/"}
    },
    {
        "game_id": "the-witcher-3",
        "title": "The Witcher 3: Wild Hunt",
        "platforms": ["pc", "playstation", "xbox", "switch"],
        "release_year": 2015,
        "genre_tags": ["rpg", "action", "open-world", "fantasy"],
        "time_tags": [60, 90],
        "energy_level": "medium",
        "mood_tags": ["immersive", "story-driven", "epic"],
        "play_style": ["narrative", "action"],
        "time_to_fun": "medium",
        "stop_friendliness": "anytime",
        "multiplayer_modes": ["solo"],
        "description_short": "Hunt monsters as Geralt in this beloved open-world RPG.",
        "fun_fact": "The Blood and Wine DLC is longer than most full games.",
        "explanation_templates": {"time_fit": "Quests vary from 15 minutes to hours.", "mood_fit": "Rich story and world.", "stop_fit": "Save anywhere."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/292030/The_Witcher_3_Wild_Hunt/"}
    },
    {
        "game_id": "diablo-4",
        "title": "Diablo IV",
        "platforms": ["pc", "playstation", "xbox"],
        "release_year": 2023,
        "genre_tags": ["rpg", "action", "arpg", "loot"],
        "time_tags": [30, 60, 90],
        "energy_level": "medium",
        "mood_tags": ["dark", "action-packed", "grinding"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "online_coop"],
        "description_short": "Dark action RPG with endless demon slaying.",
        "fun_fact": "Features a shared open world with other players.",
        "explanation_templates": {"time_fit": "Dungeons take 15-30 minutes.", "mood_fit": "Satisfying combat and loot.", "stop_fit": "Stop between dungeons."},
        "subscription_services": ["game_pass"],
        "store_links": {"steam": "https://store.steampowered.com/app/2344520/Diablo_IV/"}
    },

    # === ROGUELIKE GAMES ===
    {
        "game_id": "hades",
        "title": "Hades",
        "platforms": ["pc", "playstation", "xbox", "switch"],
        "release_year": 2020,
        "genre_tags": ["roguelike", "action", "indie"],
        "time_tags": [30, 60],
        "energy_level": "high",
        "mood_tags": ["action-packed", "story-driven", "addictive"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo"],
        "description_short": "Escape the Underworld as Zagreus, son of Hades.",
        "fun_fact": "Story progresses even when you die.",
        "explanation_templates": {"time_fit": "Runs take 20-40 minutes.", "mood_fit": "Fast roguelike action.", "stop_fit": "Each run is self-contained."},
        "subscription_services": ["game_pass"],
        "store_links": {"steam": "https://store.steampowered.com/app/1145360/Hades/"}
    },
    {
        "game_id": "slay-the-spire",
        "title": "Slay the Spire",
        "platforms": ["pc", "playstation", "xbox", "switch", "mobile"],
        "release_year": 2019,
        "genre_tags": ["roguelike", "card", "strategy", "indie"],
        "time_tags": [30, 60],
        "energy_level": "medium",
        "mood_tags": ["strategic", "addictive", "challenging"],
        "play_style": ["card_game", "strategy"],
        "time_to_fun": "short",
        "stop_friendliness": "anytime",
        "multiplayer_modes": ["solo"],
        "description_short": "Build a deck and climb the Spire in this roguelike.",
        "fun_fact": "Pioneered the roguelike deckbuilder genre.",
        "explanation_templates": {"time_fit": "Runs take 45-60 minutes.", "mood_fit": "Strategic deckbuilding.", "stop_fit": "Save and quit anytime."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/646570/Slay_the_Spire/"}
    },
    {
        "game_id": "vampire-survivors",
        "title": "Vampire Survivors",
        "platforms": ["pc", "xbox", "switch", "mobile"],
        "release_year": 2022,
        "genre_tags": ["roguelike", "action", "survival", "indie"],
        "time_tags": [15, 30],
        "energy_level": "medium",
        "mood_tags": ["addictive", "satisfying", "chaotic"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "local_coop"],
        "description_short": "Survive waves of monsters with auto-attacking weapons.",
        "fun_fact": "Made by one developer and spawned an entire genre.",
        "explanation_templates": {"time_fit": "Runs last exactly 30 minutes.", "mood_fit": "Satisfying horde survival.", "stop_fit": "Each run is self-contained."},
        "subscription_services": ["game_pass"],
        "store_links": {"steam": "https://store.steampowered.com/app/1794680/Vampire_Survivors/"}
    },
    {
        "game_id": "risk-of-rain-2",
        "title": "Risk of Rain 2",
        "platforms": ["pc", "playstation", "xbox", "switch"],
        "release_year": 2020,
        "genre_tags": ["roguelike", "action", "shooter", "co-op"],
        "time_tags": [30, 60],
        "energy_level": "high",
        "mood_tags": ["chaotic", "exciting", "cooperative"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "commitment",
        "multiplayer_modes": ["solo", "online_coop"],
        "description_short": "Third-person roguelike shooter with stacking power-ups.",
        "fun_fact": "Items stack infinitely, creating insane builds.",
        "explanation_templates": {"time_fit": "Runs last 30-60 minutes.", "mood_fit": "Chaotic power scaling.", "stop_fit": "Commit to finishing runs."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/632360/Risk_of_Rain_2/"}
    },

    # === SURVIVAL GAMES ===
    {
        "game_id": "subnautica",
        "title": "Subnautica",
        "platforms": ["pc", "playstation", "xbox", "switch"],
        "release_year": 2018,
        "genre_tags": ["survival", "exploration", "underwater", "open-world"],
        "time_tags": [60, 90],
        "energy_level": "medium",
        "mood_tags": ["immersive", "mysterious", "tense"],
        "play_style": ["sandbox_creative"],
        "time_to_fun": "medium",
        "stop_friendliness": "anytime",
        "multiplayer_modes": ["solo"],
        "description_short": "Survive on an alien ocean planet.",
        "fun_fact": "The deeper you go, the more terrifying it becomes.",
        "explanation_templates": {"time_fit": "Explore at your own pace.", "mood_fit": "Mysterious underwater survival.", "stop_fit": "Save anytime."},
        "subscription_services": ["game_pass"],
        "store_links": {"steam": "https://store.steampowered.com/app/264710/Subnautica/"}
    },
    {
        "game_id": "valheim",
        "title": "Valheim",
        "platforms": ["pc", "xbox"],
        "release_year": 2021,
        "genre_tags": ["survival", "crafting", "viking", "co-op"],
        "time_tags": [60, 90],
        "energy_level": "medium",
        "mood_tags": ["adventurous", "cooperative", "challenging"],
        "play_style": ["sandbox_creative", "action"],
        "time_to_fun": "medium",
        "stop_friendliness": "anytime",
        "multiplayer_modes": ["solo", "online_coop"],
        "description_short": "Viking survival and exploration in a procedural world.",
        "fun_fact": "Sold 10 million copies in early access.",
        "explanation_templates": {"time_fit": "Play at your own pace.", "mood_fit": "Viking adventure with friends.", "stop_fit": "Save and quit anytime."},
        "subscription_services": ["game_pass"],
        "store_links": {"steam": "https://store.steampowered.com/app/892970/Valheim/"}
    },
    {
        "game_id": "the-forest",
        "title": "The Forest",
        "platforms": ["pc", "playstation"],
        "release_year": 2018,
        "genre_tags": ["survival", "horror", "crafting", "open-world"],
        "time_tags": [60, 90],
        "energy_level": "high",
        "mood_tags": ["tense", "scary", "survival"],
        "play_style": ["action", "sandbox_creative"],
        "time_to_fun": "medium",
        "stop_friendliness": "anytime",
        "multiplayer_modes": ["solo", "online_coop"],
        "description_short": "Survive in a forest inhabited by cannibalistic mutants.",
        "fun_fact": "Has an actual ending and story to discover.",
        "explanation_templates": {"time_fit": "Play sessions at your pace.", "mood_fit": "Tense survival horror.", "stop_fit": "Save in shelters."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/242760/The_Forest/"}
    },
    {
        "game_id": "rust",
        "title": "Rust",
        "platforms": ["pc", "playstation", "xbox"],
        "release_year": 2018,
        "genre_tags": ["survival", "multiplayer", "crafting", "pvp"],
        "time_tags": [60, 90],
        "energy_level": "high",
        "mood_tags": ["intense", "competitive", "social"],
        "play_style": ["action", "sandbox_creative"],
        "time_to_fun": "medium",
        "stop_friendliness": "commitment",
        "multiplayer_modes": ["competitive", "online_coop"],
        "description_short": "Survive against players and the environment.",
        "fun_fact": "Your base can be raided while you're offline.",
        "explanation_templates": {"time_fit": "Sessions can last hours.", "mood_fit": "Intense multiplayer survival.", "stop_fit": "Progress persists on servers."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/252490/Rust/"}
    },
    {
        "game_id": "dont-starve-together",
        "title": "Don't Starve Together",
        "platforms": ["pc", "playstation", "xbox", "switch"],
        "release_year": 2016,
        "genre_tags": ["survival", "crafting", "co-op", "indie"],
        "time_tags": [60, 90],
        "energy_level": "medium",
        "mood_tags": ["challenging", "quirky", "cooperative"],
        "play_style": ["sandbox_creative"],
        "time_to_fun": "medium",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "online_coop"],
        "description_short": "Survive a strange wilderness with friends.",
        "fun_fact": "The art style is inspired by Tim Burton.",
        "explanation_templates": {"time_fit": "Days provide natural breaks.", "mood_fit": "Quirky survival challenge.", "stop_fit": "Save at night."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/322330/Dont_Starve_Together/"}
    },
]

# Mobile-specific games to fill platform gaps
MOBILE_FILL_GAMES = [
    # Horror on Mobile
    {
        "game_id": "dead-by-daylight-mobile",
        "title": "Dead by Daylight Mobile",
        "platforms": ["mobile"],
        "release_year": 2020,
        "genre_tags": ["horror", "multiplayer", "survival", "asymmetric"],
        "time_tags": [15, 30],
        "energy_level": "high",
        "mood_tags": ["scary", "tense", "competitive"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["competitive"],
        "description_short": "4v1 horror where survivors face off against killers.",
        "fun_fact": "Features iconic killers from horror movies.",
        "explanation_templates": {"time_fit": "Matches take 10-15 minutes.", "mood_fit": "Tense asymmetric horror.", "stop_fit": "Complete matches then stop."},
        "subscription_services": [],
        "store_links": {}
    },
    {
        "game_id": "identity-v",
        "title": "Identity V",
        "platforms": ["mobile", "pc"],
        "release_year": 2018,
        "genre_tags": ["horror", "multiplayer", "asymmetric", "gothic"],
        "time_tags": [15, 30],
        "energy_level": "medium",
        "mood_tags": ["creepy", "competitive", "strategic"],
        "play_style": ["action", "strategy"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["competitive"],
        "description_short": "Gothic horror asymmetric game from NetEase.",
        "fun_fact": "Features a unique Tim Burton-esque art style.",
        "explanation_templates": {"time_fit": "Matches take 8-12 minutes.", "mood_fit": "Stylish horror gameplay.", "stop_fit": "Complete matches then stop."},
        "subscription_services": [],
        "store_links": {}
    },
    {
        "game_id": "granny",
        "title": "Granny",
        "platforms": ["mobile"],
        "release_year": 2017,
        "genre_tags": ["horror", "puzzle", "escape-room", "stealth"],
        "time_tags": [15, 30],
        "energy_level": "high",
        "mood_tags": ["scary", "tense", "puzzle-solving"],
        "play_style": ["puzzle"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo"],
        "description_short": "Escape from Granny's house in 5 days.",
        "fun_fact": "Became a viral sensation with YouTubers.",
        "explanation_templates": {"time_fit": "Escape attempts take 10-20 minutes.", "mood_fit": "Tense escape horror.", "stop_fit": "Each attempt is self-contained."},
        "subscription_services": [],
        "store_links": {}
    },
    # FPS on Mobile
    {
        "game_id": "modern-combat-5",
        "title": "Modern Combat 5",
        "platforms": ["mobile"],
        "release_year": 2014,
        "genre_tags": ["fps", "shooter", "military"],
        "time_tags": [15, 30],
        "energy_level": "high",
        "mood_tags": ["action-packed", "competitive"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "competitive"],
        "description_short": "Console-quality FPS action on mobile.",
        "fun_fact": "One of the first AAA-quality mobile shooters.",
        "explanation_templates": {"time_fit": "Missions take 10-15 minutes.", "mood_fit": "Intense FPS action.", "stop_fit": "Complete missions then stop."},
        "subscription_services": [],
        "store_links": {}
    },
    {
        "game_id": "critical-ops",
        "title": "Critical Ops",
        "platforms": ["mobile"],
        "release_year": 2015,
        "genre_tags": ["fps", "shooter", "competitive", "tactical"],
        "time_tags": [15, 30],
        "energy_level": "high",
        "mood_tags": ["competitive", "tactical"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["competitive"],
        "description_short": "Counter-Strike-style tactical shooter for mobile.",
        "fun_fact": "Has a thriving esports scene.",
        "explanation_templates": {"time_fit": "Matches take 10-15 minutes.", "mood_fit": "Tactical team combat.", "stop_fit": "Complete matches then stop."},
        "subscription_services": [],
        "store_links": {}
    },
    # Racing on Mobile
    {
        "game_id": "real-racing-3",
        "title": "Real Racing 3",
        "platforms": ["mobile"],
        "release_year": 2013,
        "genre_tags": ["racing", "simulation", "cars"],
        "time_tags": [15, 30],
        "energy_level": "medium",
        "mood_tags": ["competitive", "realistic"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo", "competitive"],
        "description_short": "Console-quality racing simulation on mobile.",
        "fun_fact": "Features real tracks and over 300 licensed cars.",
        "explanation_templates": {"time_fit": "Races take 3-5 minutes.", "mood_fit": "Realistic racing action.", "stop_fit": "Complete races then stop."},
        "subscription_services": [],
        "store_links": {}
    },
    {
        "game_id": "mario-kart-tour",
        "title": "Mario Kart Tour",
        "platforms": ["mobile"],
        "release_year": 2019,
        "genre_tags": ["racing", "kart", "arcade"],
        "time_tags": [15],
        "energy_level": "medium",
        "mood_tags": ["fun", "competitive", "casual"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "anytime",
        "multiplayer_modes": ["solo", "competitive"],
        "description_short": "Mario Kart racing designed for mobile.",
        "fun_fact": "Courses are based on real-world cities.",
        "explanation_templates": {"time_fit": "Races take 2-3 minutes.", "mood_fit": "Quick kart racing fun.", "stop_fit": "Stop after any race."},
        "subscription_services": [],
        "store_links": {}
    },
    {
        "game_id": "csr-racing-2",
        "title": "CSR Racing 2",
        "platforms": ["mobile"],
        "release_year": 2016,
        "genre_tags": ["racing", "drag-racing", "cars"],
        "time_tags": [15],
        "energy_level": "medium",
        "mood_tags": ["competitive", "collecting"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "anytime",
        "multiplayer_modes": ["solo", "competitive"],
        "description_short": "Drag racing with hyper-realistic graphics.",
        "fun_fact": "Features officially licensed supercars.",
        "explanation_templates": {"time_fit": "Races take under a minute.", "mood_fit": "Quick drag racing thrills.", "stop_fit": "Stop after any race."},
        "subscription_services": [],
        "store_links": {}
    },
    # Sports on Mobile
    {
        "game_id": "retro-goal",
        "title": "Retro Goal",
        "platforms": ["mobile"],
        "release_year": 2020,
        "genre_tags": ["sports", "soccer", "retro", "arcade"],
        "time_tags": [15, 30],
        "energy_level": "medium",
        "mood_tags": ["fun", "nostalgic", "casual"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo"],
        "description_short": "Retro-style soccer with arcade gameplay.",
        "fun_fact": "From the makers of Retro Bowl.",
        "explanation_templates": {"time_fit": "Matches take 5-10 minutes.", "mood_fit": "Quick retro soccer fun.", "stop_fit": "Complete matches then stop."},
        "subscription_services": [],
        "store_links": {}
    },
    {
        "game_id": "baseball-9",
        "title": "Baseball 9",
        "platforms": ["mobile"],
        "release_year": 2018,
        "genre_tags": ["sports", "baseball", "arcade"],
        "time_tags": [15, 30],
        "energy_level": "medium",
        "mood_tags": ["fun", "casual", "sports"],
        "play_style": ["action"],
        "time_to_fun": "short",
        "stop_friendliness": "checkpoints",
        "multiplayer_modes": ["solo"],
        "description_short": "Accessible arcade baseball with team management.",
        "fun_fact": "One of the most downloaded baseball games on mobile.",
        "explanation_templates": {"time_fit": "Games take 10-15 minutes.", "mood_fit": "Quick baseball action.", "stop_fit": "Complete games then stop."},
        "subscription_services": [],
        "store_links": {}
    },
    # Strategy Mobile
    {
        "game_id": "teamfight-tactics",
        "title": "Teamfight Tactics",
        "platforms": ["pc", "mobile"],
        "release_year": 2019,
        "genre_tags": ["strategy", "auto-battler", "competitive"],
        "time_tags": [30, 60],
        "energy_level": "medium",
        "mood_tags": ["strategic", "competitive"],
        "play_style": ["strategy"],
        "time_to_fun": "short",
        "stop_friendliness": "commitment",
        "multiplayer_modes": ["competitive"],
        "description_short": "League of Legends auto-battler.",
        "fun_fact": "One of the most popular auto-battlers worldwide.",
        "explanation_templates": {"time_fit": "Games take 25-35 minutes.", "mood_fit": "Strategic auto-battling.", "stop_fit": "Commit to full games."},
        "subscription_services": [],
        "store_links": {}
    },
    # Card games
    {
        "game_id": "balatro-mobile",
        "title": "Balatro",
        "platforms": ["pc", "playstation", "xbox", "switch", "mobile"],
        "release_year": 2024,
        "genre_tags": ["card", "roguelike", "poker", "indie"],
        "time_tags": [30, 60],
        "energy_level": "low",
        "mood_tags": ["strategic", "addictive", "relaxing"],
        "play_style": ["card_game", "strategy"],
        "time_to_fun": "short",
        "stop_friendliness": "anytime",
        "multiplayer_modes": ["solo"],
        "description_short": "Poker-based roguelike deckbuilder.",
        "fun_fact": "Uses poker hands but adds wild modifiers called Jokers.",
        "explanation_templates": {"time_fit": "Runs take 30-45 minutes.", "mood_fit": "Addictive poker roguelike.", "stop_fit": "Save and quit anytime."},
        "subscription_services": [],
        "store_links": {"steam": "https://store.steampowered.com/app/2379780/Balatro/"}
    },
]

def add_games():
    added = 0
    skipped = 0
    updated = 0

    all_games = GENRE_FILL_GAMES + MOBILE_FILL_GAMES

    for game in all_games:
        game_id = game["game_id"]

        existing = games_ref.document(game_id).get()
        if existing.exists:
            print(f"Skipping {game['title']} - already exists")
            skipped += 1
            continue

        # Add timestamps
        game["created_at"] = datetime.now(timezone.utc)
        game["updated_at"] = datetime.now(timezone.utc)

        games_ref.document(game_id).set(game)
        print(f"Added: {game['title']}")
        added += 1

    print(f"\nDone! Added {added} games, skipped {skipped} existing")

if __name__ == "__main__":
    add_games()
